# assign_user_themes.py
#
# This script calculates the closest N themes for each user based on their
# UMAP embeddings and pre-defined theme centroids. It then generates
# wrangler commands to store these top N themes in Cloudflare KV.
#
# Before running:
# 1. Ensure 'theme_definitions.json' has been MANUALLY UPDATED with meaningful
#    theme labels for each cluster ID. The quality of these labels is crucial.
# 2. Ensure the Cloudflare KV namespace specified in KV_NAMESPACE_BINDING
#    (default: 'USER_TOP_THEMES') has been created in your Cloudflare account.
#    You can create it using: wrangler kv:namespace create USER_TOP_THEMES
# 3. Ensure 'wrangler' is installed, configured, and authenticated to access
#    your Cloudflare account.
# 4. Ensure 'user_umap_embeddings.json' (generated by analyze_user_themes.py)
#    is present in the same directory.

import json
import numpy as np # For linalg.norm or math.sqrt
import subprocess # Will be used to construct command, not run directly
import sys
import math # For math.sqrt

# --- Configuration Variables ---
N_TOP_THEMES = 3  # Number of top themes to assign to each user
USER_EMBEDDINGS_FILE = 'user_umap_embeddings.json'
THEME_DEFINITIONS_FILE = 'theme_definitions.json' # Manually curated theme labels and centroids
KV_NAMESPACE_BINDING = 'USER_TOP_THEMES' # Target KV namespace binding

def load_json_file(filename):
    """
    Loads a JSON file and returns its content.

    Args:
        filename (str): The path to the JSON file.

    Returns:
        dict or list: The parsed JSON content, or None if an error occurs.
    """
    print(f"Loading JSON file: {filename}...")
    try:
        with open(filename, 'r') as f:
            data = json.load(f)
        print(f"Successfully loaded {filename}.")
        return data
    except FileNotFoundError:
        print(f"Error: File not found: '{filename}'.")
        return None
    except json.JSONDecodeError as e:
        print(f"Error: Could not decode JSON from '{filename}': {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred while loading '{filename}': {e}")
        return None

def calculate_distance(point1, point2):
    """
    Calculates the Euclidean distance between two 2D points.

    Args:
        point1 (list or tuple): The coordinates of the first point [x1, y1].
        point2 (list or tuple): The coordinates of the second point [x2, y2].

    Returns:
        float: The Euclidean distance.
    """
    if len(point1) != 2 or len(point2) != 2:
        raise ValueError("Points must be 2-dimensional.")
    return math.sqrt((point2[0] - point1[0])**2 + (point2[1] - point1[1])**2)

def main():
    """
    Main execution block to assign top N themes to users.
    """
    print("Starting assignment of top themes to users...")

    # Load user UMAP embeddings
    user_embeddings = load_json_file(USER_EMBEDDINGS_FILE)
    if user_embeddings is None:
        print(f"Could not load user embeddings from '{USER_EMBEDDINGS_FILE}'. Exiting.")
        sys.exit(1)
    if not user_embeddings:
        print(f"User embeddings file '{USER_EMBEDDINGS_FILE}' is empty. No users to process. Exiting.")
        sys.exit(1)

    # Load theme definitions (manually curated)
    # Expected format: {"cluster_id_str": {"themeLabel": "...", "centroid": [cx, cy]}, ...}
    theme_definitions = load_json_file(THEME_DEFINITIONS_FILE)
    if theme_definitions is None:
        print(f"Could not load theme definitions from '{THEME_DEFINITIONS_FILE}'. Exiting.")
        sys.exit(1)
    if not theme_definitions:
        print(f"Theme definitions file '{THEME_DEFINITIONS_FILE}' is empty. No themes to assign. Exiting.")
        sys.exit(1)
    
    # Validate theme definitions structure (basic check)
    first_theme_key = next(iter(theme_definitions))
    if not isinstance(theme_definitions[first_theme_key], dict) or \
       'themeLabel' not in theme_definitions[first_theme_key] or \
       'centroid' not in theme_definitions[first_theme_key]:
        print(f"Error: Theme definitions in '{THEME_DEFINITIONS_FILE}' do not seem to have the expected structure "
              f"('themeLabel', 'centroid'). Example valid entry: "
              f"\"0\": {{\"themeLabel\": \"Tech Enthusiasts\", \"centroid\": [1.2, 3.4]}}")
        sys.exit(1)

    print(f"\nFound {len(user_embeddings)} users and {len(theme_definitions)} themes.")
    print(f"Will assign top {N_TOP_THEMES} themes to each user.")
    print("Generating wrangler commands (these commands are NOT executed by the script):\n")

    commands_generated = 0
    for user_id, user_embedding_coords in user_embeddings.items():
        if not isinstance(user_embedding_coords, list) or len(user_embedding_coords) != 2:
            print(f"Warning: Skipping user '{user_id}' due to invalid embedding format: {user_embedding_coords}")
            continue

        user_theme_distances = []
        for cluster_id_str, theme_data in theme_definitions.items():
            try:
                theme_label = theme_data['themeLabel']
                theme_centroid = theme_data['centroid']
                
                if not isinstance(theme_centroid, list) or len(theme_centroid) != 2:
                    print(f"Warning: Skipping theme '{theme_label}' (Cluster ID: {cluster_id_str}) for user '{user_id}' "
                          f"due to invalid centroid format: {theme_centroid}")
                    continue

                distance = calculate_distance(user_embedding_coords, theme_centroid)
                user_theme_distances.append({
                    "themeLabel": theme_label,
                    "clusterId": int(cluster_id_str), # Store original cluster ID as integer
                    "distance": distance
                })
            except KeyError:
                print(f"Warning: Skipping theme with cluster ID '{cluster_id_str}' due to missing 'themeLabel' or 'centroid'.")
                continue
            except ValueError as ve: # From calculate_distance or int conversion
                 print(f"Warning: Error processing theme '{cluster_id_str}' for user '{user_id}': {ve}")
                 continue


        if not user_theme_distances:
            print(f"Warning: No valid themes found to calculate distances for user '{user_id}'. Skipping.")
            continue
            
        # Sort themes by distance (ascending)
        user_theme_distances.sort(key=lambda x: x['distance'])

        # Select top N themes
        top_n_themes = user_theme_distances[:N_TOP_THEMES]

        # Format as a compact JSON string for KV store
        # We only need themeLabel and clusterId for the KV store, distance was for sorting.
        # Example: [{"themeLabel": "Techno", "clusterId": 0}, {"themeLabel": "Foodies", "clusterId": 3}]
        kv_payload = [{"themeLabel": t["themeLabel"], "clusterId": t["clusterId"]} for t in top_n_themes]
        json_payload_for_kv = json.dumps(kv_payload, separators=(',', ':')) # Compact JSON

        # Construct the wrangler command
        # Ensure user_id and json_payload are properly quoted for shell.
        # User IDs might contain characters that need quoting.
        # JSON payload definitely needs single quotes around it.
        # A common robust way for user_id is to single quote it if it's simple,
        # or use more complex shell escaping if it can be arbitrary.
        # For this script, we'll assume user_ids are simple enough for direct insertion
        # or that users will verify. If user_ids can be complex, consider `shlex.quote`.
        
        # Simplistic quoting for user_id: if it's alphanumeric, no quotes needed.
        # Otherwise, wrap in single quotes. This is not perfectly robust for all shell chars.
        quoted_user_id = f"'{user_id}'" if not user_id.isalnum() else user_id

        wrangler_command = (
            f"wrangler kv:key put --binding={KV_NAMESPACE_BINDING} "
            f"{quoted_user_id} '{json_payload_for_kv}'"
        )

        print(f"# Command for user: {user_id}")
        print(wrangler_command)
        print("-" * 20)
        commands_generated += 1

    if commands_generated > 0:
        print(f"\nSuccessfully generated {commands_generated} wrangler commands.")
        print("Please review the commands above. You can copy and paste them into your terminal")
        print("or save them to a shell script to execute them.")
    else:
        print("\nNo wrangler commands were generated. Check input files and warnings.")
        
    print("\nFinished assigning themes.")

if __name__ == "__main__":
    main()
