[package]
name = "rust-test-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6", features = ["d1"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
