//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "d1_migrations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub name: Option<String>,
    pub applied_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
