//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "draft_post_hashtag")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub draft_post_id: String,
    #[sea_orm(column_type = "Text")]
    pub hashtag_id: String,
    #[sea_orm(column_type = "custom(\"numeric\")")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::draft_post::Entity",
        from = "Column::DraftPostId",
        to = "super::draft_post::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DraftPost,
    #[sea_orm(
        belongs_to = "super::hashtag::Entity",
        from = "Column::HashtagId",
        to = "super::hashtag::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hashtag,
}

impl Related<super::draft_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftPost.def()
    }
}

impl Related<super::hashtag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hashtag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
